language: python
sudo: required
dist: xenial

arch:
    - amd64
    - arm64

python:
  - 3.5.3  # minimum for aiohttp=3 and async-timeout=3
  - 3.5
  - 3.6.3
  - 3.6
  - 3.7
  - 3.8
  - 3.9-dev
  - nightly
git:
  depth: 9999

before_install:
  # temporary workaround for s390x and arm64 permissions problem
  # https://travis-ci.community/t/permission-issue-while-building-wheels-for-various-python-packages/7822/12
  - sudo chown -Rv $USER:$GROUP ~/.cache/pip/wheels

install:
  - pip install cython  # does not fix reppy for python 3.9
  - pip install -r requirements.txt

script:
  - make test_coverage
after_success:
  coveralls
